# Generated by Django 4.2 on 2023-04-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ea3repo.level'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ea3repo.layer'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ea3repo.level'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
