# Generated by Django 4.2 on 2023-04-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repo', '0002_layer_level_alter_artifact_layer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='layer',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='level',
            field=models.ForeignKey(default='GI', on_delete=django.db.models.deletion.CASCADE, to='ea3repo.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('GI', 'Goals & Initiatives'), ('PS', 'Products & Services'), ('DI', 'Data & Information'), ('SA', 'Systems & Application'), ('NI', 'Networks & Infrastructure')], default='GI', max_length=2),
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
