# Generated by Django 4.2 on 2023-04-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repo', '0003_remove_artifact_layer_alter_artifact_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ea3repo.level')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ea3repo.layer'),
        ),
    ]
