# Generated by Django 4.2 on 2023-04-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repo', '0004_layer_artifact_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='layer',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
