# Generated by Django 4.2 on 2023-04-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repo', '0005_remove_artifact_layer_delete_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='level',
            field=models.ForeignKey(default='Goals & Initiatives', on_delete=django.db.models.deletion.CASCADE, to='ea3repo.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Goals & Initiatives', 'Goals & Initiatives'), ('Products & Services', 'Products & Services'), ('Data & Information', 'Data & Information'), ('Systems & Application', 'Systems & Application'), ('Networks & Infrastructure', 'Networks & Infrastructure')], default='Goals & Initiatives', max_length=30),
        ),
    ]
