# Generated by Django 4.2 on 2023-04-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repo', '0006_alter_artifact_level_alter_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artifact',
            name='use_frequency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
